#!/usr/bin/with-contenv bash

s6-echo "Starting lighttpd"

# Touch log files to ensure they exist (create if non-existing, preserve if existing)
touch /var/log/lighttpd/access.log /var/log/lighttpd/error.log

# Ensure that permissions are set so that lighttpd can write to the logs
chown -R www-data:www-data /var/log/lighttpd
chmod 0644 /var/log/lighttpd/access.log /var/log/lighttpd/error.log

lighttpd -D -f /etc/lighttpd/lighttpd.conf
