FROM multiarch/debian-debootstrap:armel-stretch-slim as build
WORKDIR /tmp

RUN apt-get update && apt-get install --no-install-recommends -y build-essential libgmp-dev m4 ca-certificates
RUN wget https://ftp.gnu.org/gnu/nettle/nettle-3.4.tar.gz && tar -xzf nettle-3.4.tar.gz && cd nettle-3.4 && ./configure && \
    make && make install

RUN wget https://github.com/pi-hole/FTL/archive/v4.3.1.tar.gz && mkdir -p v4.3.1 && \
    tar -xzf v4.3.1.tar.gz -C v4.3.1 --strip-components 1 && cd v4.3.1 && \
    make

FROM multiarch/debian-debootstrap:armel-stretch-slim

ENV S6OVERLAY_RELEASE https://github.com/just-containers/s6-overlay/releases/download/v1.21.7.0/s6-overlay-arm.tar.gz
COPY install.sh /usr/local/bin/install.sh
COPY VERSION /etc/docker-pi-hole-version
ENV PIHOLE_INSTALL /root/ph_install.sh

RUN bash -ex install.sh 2>&1 && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

ENTRYPOINT [ "/s6-init" ]

ADD s6/debian-root /
COPY s6/service /usr/local/bin/service

# php config start passes special ENVs into
ENV PHP_ENV_CONFIG '/etc/lighttpd/conf-enabled/15-fastcgi-php.conf'
ENV PHP_ERROR_LOG '/var/log/lighttpd/error.log'
COPY ./start.sh /
COPY ./bash_functions.sh /
COPY --from=build /tmp/v4.3.1/pihole-FTL /tmp/v4.3.1/dnsmasq /usr/bin/ 

# IPv6 disable flag for networks/devices that do not support it
ENV IPv6 True

EXPOSE 53 53/udp
EXPOSE 67/udp
EXPOSE 80
EXPOSE 443

ENV S6_LOGGING 0
ENV S6_KEEP_ENV 1
ENV S6_BEHAVIOUR_IF_STAGE2_FAILS 2

ENV ServerIP 0.0.0.0
ENV FTL_CMD no-daemon
ENV DNSMASQ_USER root

ENV VERSION v4.3.1
ENV ARCH armel
ENV PATH /opt/pihole:${PATH}

LABEL image="pihole/pihole:v4.3.1_armel"
LABEL maintainer="adam@diginc.us"
LABEL url="https://www.github.com/pi-hole/docker-pi-hole"

HEALTHCHECK CMD dig @127.0.0.1 pi.hole || exit 1

SHELL ["/bin/bash", "-c"]