#!/command/with-contenv bash

if [ "${PH_VERBOSE:-0}" -gt 0 ] ; then
    set -x ;
fi

[[ ! -d /var/cache/lighttpd/uploads ]] && mkdir -p /var/cache/lighttpd/uploads || true

if [[ 1 -eq ${WEBLOGS_STDOUT:-0} ]]; then
  #lighthttpd cannot use /dev/stdout https://redmine.lighttpd.net/issues/2731
  touch /etc/s6-overlay/s6-rc.d/user/contents.d/{lighttpd-access-log,lighttpd-error-log}
  service lighttpd-access-log start
  service lighttpd-error-log start
else
  rm -f /etc/s6-overlay/s6-rc.d/user/contents.d/{lighttpd-access-log,lighttpd-error-log}
  #remove fifo if exists
  [[ -p /var/log/lighttpd/access.log ]] && rm -Rf /var/log/lighttpd/access.log
  [[ -p  /var/log/lighttpd/error.log ]] && rm -Rf /var/log/lighttpd/error.log
  # Touch log files to ensure they exist (create if non-existing, preserve if existing)
  touch /var/log/lighttpd/access.log /var/log/lighttpd/error.log

  # Ensure that permissions are set so that lighttpd can write to the logs
  chmod 0644 /var/log/lighttpd/access.log /var/log/lighttpd/error.log
fi

chown -R www-data:www-data /var/log/lighttpd
lighttpd -D -f /etc/lighttpd/lighttpd.conf
