#!/usr/bin/with-contenv bash

piholeFtlPid=$(pgrep pihole-FTL)
if [ $? -eq 0 ]; then
    s6-echo "Stopping pihole-FTL ($piholeFtlPid)"
    kill -9 $piholeFtlPid
else
    s6-echo "Process for pihole-FTL not found."
fi
