#!/usr/bin/with-contenv bash

s6-echo "Starting pihole-FTL ($FTL_CMD)"

# debug is the current default, but this hammers SD cards so disabling all output other than log files
s6-setuidgid root pihole-FTL $FTL_CMD >/dev/null 2>&1
