name: Remove untagged images from registry
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    housekeeping:
        runs-on: ubuntu-latest
        steps:
            -
                name: Delete all containers from repository without tags
                uses: Chizkiyahu/delete-untagged-ghcr-action@68758dd8caf1d9dbaed1fe9cc1a1f8fcea1c4cf0 #v6.1.0
                with:
                    token: ${{ secrets.PAT_TOKEN }}
                    repository_owner: ${{ github.repository_owner }}
                    repository: ${{ github.repository }}
                    untagged_only: true
                    owner_type: org # or user
                    except_untagged_multiplatform: true
